INSERT INTO cars (brand, model, body_type, engine_capacity, fuel_type)
VALUES ('Toyota', 'Corolla', 'SEDAN', 1.6, 'PETROL'),
       ('Ford', 'F-150', 'PICKUP', 5.0, 'PETROL'),
       ('Honda', 'Civic', 'SEDAN', 1.8, 'PETROL'),
       ('Volkswagen', 'Passat', 'STATION_WAGON', 2.0, 'DIESEL'),
       ('Chrysler', 'Pacifica', 'MINIVAN', 3.6, 'PETROL'),
       ('Chevrolet', 'Silverado', 'PICKUP', 6.2, 'PETROL'),
       ('Audi', 'A4', 'SEDAN', 2.0, 'DIESEL'),
       ('Nissan', 'Altima', 'SEDAN', 2.5, 'PETROL'),
       ('BMW', '3 Series', 'SEDAN', 2.0, 'DIESEL'),
       ('Mercedes-Benz', 'E-Class', 'SEDAN', 3.0, 'DIESEL'),
       ('Ram', '1500', 'PICKUP', 5.7, 'PETROL'),
       ('Hyundai', 'Elantra', 'SEDAN', 2.0, 'PETROL'),
       ('Kia', 'Sedona', 'MINIVAN', 3.3, 'PETROL'),
       ('Subaru', 'Outback', 'STATION_WAGON', 2.5, 'PETROL'),
       ('Mazda', 'CX-5', 'STATION_WAGON', 2.5, 'PETROL'),
       ('Jeep', 'Wrangler', 'SUV', 3.6, 'PETROL'),
       ('Mitsubishi', 'L200', 'PICKUP', 2.4, 'DIESEL'),
       ('Volvo', 'V60', 'STATION_WAGON', 2.0, 'DIESEL'),
       ('Lexus', 'RX', 'SUV', 3.5, 'PETROL'),
       ('Land Rover', 'Discovery', 'SUV', 3.0, 'DIESEL'),
       ('Porsche', 'Cayenne', 'SUV', 3.0, 'PETROL'),
       ('Fiat', '500L', 'MINIVAN', 1.4, 'PETROL'),
       ('Acura', 'MDX', 'SUV', 3.5, 'PETROL'),
       ('Infiniti', 'QX80', 'SUV', 5.6, 'PETROL'),
       ('Buick', 'Enclave', 'SUV', 3.6, 'PETROL'),
       ('Lincoln', 'Navigator', 'SUV', 3.5, 'PETROL'),
       ('GMC', 'Yukon', 'SUV', 5.3, 'PETROL'),
       ('Cadillac', 'Escalade', 'SUV', 6.2, 'PETROL'),
       ('Jaguar', 'F-PACE', 'SUV', 2.0, 'DIESEL'),
       ('Bentley', 'Bentayga', 'SUV', 4.0, 'PETROL'),
       ('Rolls-Royce', 'Cullinan', 'SUV', 6.7, 'PETROL'),
       ('Maserati', 'Levante', 'SUV', 3.0, 'PETROL'),
       ('Alfa Romeo', 'Stelvio', 'SUV', 2.0, 'PETROL'),
       ('Lamborghini', 'Urus', 'SUV', 4.0, 'PETROL'),
       ('Ferrari', 'F8 Tributo', 'COUPE', 3.9, 'PETROL'),
       ('McLaren', '720S', 'COUPE', 4.0, 'PETROL'),
       ('Porsche', '911', 'COUPE', 3.0, 'PETROL'),
       ('BMW', 'i8', 'COUPE', 1.5, 'PETROL'),
       ('Audi', 'R8', 'COUPE', 5.2, 'PETROL');

INSERT INTO cars (id,brand, model, body_type, engine_capacity, fuel_type)
VALUES ('26635638-2f30-4891-81a0-bcac1f97b0d4','Toyota', 'Corolla', 'SEDAN', 1.6, 'PETROL'),
       ('1be4206e-787f-4708-924f-1adf9dd9a5da','Toyota', 'Corolla', 'SEDAN', 1.6, 'PETROL'),
       ('e4866644-fd55-4cfc-8e56-baff0fef3295','Toyota', 'Corolla', 'SEDAN', 1.6, 'PETROL');


